# workflow name
name: build and test the app with GUI tests


# when the workflow will be triggered
on:
  push:
    branches:
      - main

# where will the workflow run
jobs:
  run_unit_tests:
    runs-on: macos-latest
    steps:
      # checkout repository
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Run GUI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew clean connectedDebugAndroidTest